### ISSUE TITLE
Proguard issue SDK 26

### ISSUE THREAD

**Issue by httpdispatch** [JakeWharton/madge#15]
> Warning: com.jakewharton.madge.DelegateCanvas: can't find referenced method 'boolean clipRegion(android.graphics.Region,android.graphics.Region$Op)' in library class android.graphics.Canvas
> Warning: com.jakewharton.madge.DelegateCanvas: can't find referenced method 'boolean clipRegion(android.graphics.Region)' in library class android.graphics.Canvas

Solved via adding new rule to the proguard-rules
```
# Handle madge
-dontwarn com.jakewharton.madge.**
```

**Comment by JakeWharton** [comment]
Weird. Those methods are marked as deprecated but they still should be there...

**Comment by httpdispatch** [comment]
I have a revision 2 of the SDK Platform 26. Maybe that methods have been removed starting from the revision 2.

**Comment by JakeWharton** [comment]
Yep it was removed in 26. Your ProGuard rules are safe to use, as the methods won't be called when not available.

I'm not going to alter the library for now, though.

Thanks for the heads up.

**Comment by httpdispatch** [comment]
Thank you very much for the support
